class Querys:

    #Sentencias a la base de datos
    QUERY_MATERIALES = "SELECT TB_INDEX, CAT_FILA, CAT_DISCIPLINA, CAT_ITEM_CODE, CAT_SIZE, CAT_MATL_TYPE, CAT_ITEM_TYPE, CAT_DESCRIPCION, REQ_LOG, REQ_NUMERO, REQ_DESCRIPCION_SUPLEMENTO, REQ_NUMERO_1, REQ_STATUS, REQ_CANTIDAD, REQ_TOTAL, REQ_UOM, NOC, NOC_LINEA, NOC_SUB_LINEA, NOC_DESTINO, NOC_CANTIDAD, NOC_FECHA_RAS, NOC_FECHA_SOP, NOC_GRUPO_DE_EMBARQUE, NOC_CANTIDAD_GRUPO_DE_EMBARQUE, NOC_HITO, NOC_ESTATUS, NOC_FECHA, NOC_SH_HITO, NOC_SH_ESTATUS, NOC_SH_FECHA FROM MATERIALES_Y_PIEZASM"

    


